apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-rolling
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: aceest
      version: rolling
  template:
    metadata:
      labels:
        app: aceest
        version: rolling
    spec:
      containers:
      - name: aceest
        image: <REGISTRY>/aceest-fitness:rolling
        ports:
        - containerPort: 5000